- hosts: hadoop
  user: root
  vars:
    hadoop_user: root
  tasks:
  - name: check hive
    tags: ['never', 'install']
    stat:
      path: /opt/apache-hive-3.1.3-bin
    register: work_dir
  - name: install hive
    tags: ['never', 'install']
    unarchive:
      copy: yes
      src: ../../archives/apache-hive-3.1.3-bin.tar.gz
      dest: /opt/
    when: not work_dir.stat.exists
  - name: change hive bashrc
    tags: ['never', 'install']
    blockinfile:
      backup: yes
      marker: '# {mark} ANSIBLE BLOCK FOR HIVE'
      path: /etc/bashrc
      block: |
        export HIVE_HOME=/opt/apache-hive-3.1.3-bin
    when: not work_dir.stat.exists
  - name: config hive
    tags: ['never', 'config']
    template:
      src: ./conf/{{ item }}
      dest: /opt/apache-hive-3.1.3-bin/conf/{{ item }}
    with_items:
    - hive-site.xml
  - name: fixed compatible rm guava
    tags: ['never', 'fixed']
    file:
      path: /opt/apache-hive-3.1.3-bin/lib/{{ item }}
      state: absent
    with_items:
    - guava-19.0.jar
  - name: fixed compatible link hadoop
    tags: ['never', 'fixed']
    file:
      src: /opt/hadoop-3.3.6/share/hadoop/common/lib/{{ item }}
      dest: /opt/apache-hive-3.1.3-bin/lib/{{ item }}
      force: yes
      state: link
    with_items:
    - guava-27.0-jre.jar
