- hosts: hadoop
  user: root
  vars:
    hadoop_user: root
  tasks:
  - name: check hadoop
    tags: ['never', 'install']
    stat:
      path: /opt/hadoop-3.3.6
    register: work_dir
  - name: install hadoop
    tags: ['never', 'install']
    unarchive:
      copy: yes
      src: ../../archives/hadoop-3.3.6.tar.gz
      dest: /opt/
    when: not work_dir.stat.exists
  - name: change hadoop bashrc
    tags: ['never', 'install']
    blockinfile:
      backup: yes
      marker: '# {mark} ANSIBLE BLOCK FOR HADOOP'
      path: /etc/bashrc
      block: |
        export HADOOP_HOME=/opt/hadoop-3.3.6
        export HDFS_NAMENODE_USER={{ hadoop_user }}
        export HDFS_DATANODE_USER={{ hadoop_user }}
        export HDFS_SECONDARYNAMENODE_USER={{ hadoop_user }}
        export YARN_RESOURCEMANAGER_USER={{ hadoop_user }}
        export YARN_NODEMANAGER_USER={{ hadoop_user }}
        export HDFS_JOURNALNODE_USER={{ hadoop_user }}
        export HDFS_ZKFC_USER={{ hadoop_user }}
  - name: config hadoop
    tags: ['never', 'config']
    template:
      src: ./etc/{{ item }}
      dest: /opt/hadoop-3.3.6/etc/hadoop/{{ item }}
    with_items:
    - workers
    - core-site.xml
    - hdfs-site.xml
    - yarn-site.xml
