- hosts: hadoop
  user: root
  vars:
    hadoop_user: root
  tasks:
  - name: check phoenix
    tags: ['never', 'install']
    stat:
      path: /opt/phoenix-hbase-2.4-5.1.2-bin
    register: work_dir
  - name: install phoenix
    tags: ['never', 'install']
    unarchive:
      copy: yes
      src: ../../archives/phoenix-hbase-2.4-5.1.2-bin.tar.gz
      dest: /opt/
    when: not work_dir.stat.exists
  - name: link hbase
    tags: ['never', 'link']
    file:
      src: /opt/phoenix-hbase-2.4-5.1.2-bin/phoenix-server-hbase-2.4-5.1.2.jar
      dest: /opt/hbase-2.4.12/lib/phoenix-server-hbase-2.4-5.1.2.jar
      force: yes
      state: link
  - name: config phoenix cli
    tags: ['never', 'config']
    file:
      src: /opt/hbase-2.4.12/conf/hbase-site.xml
      dest: /opt/phoenix-hbase-2.4-5.1.2-bin/bin/hbase-site.xml
      force: yes
      state: link
