- hosts: etcd
  user: root
  vars:
    service_dir: "{{ fs_compose_dir }}/service/etcd"
  tasks:
  - name: make service dir
    tags: ['never', 'init']
    file:
      path: "{{ service_dir }}"
      state: directory
  
  - name: make conf dir
    tags: ['never', 'init']
    file:
      path: "{{ service_dir }}/conf"
      state: directory
  
  - name: sync ssl
    tags: ['never', 'init']
    synchronize:
      src: ./conf/ssl
      dest: "{{ service_dir }}/conf"
      delete: true
      checksum: true

  - name: copy Dockerfile
    tags: ['never', 'init']
    copy:
      src: ./Dockerfile
      dest: "{{ service_dir }}/Dockerfile"

  - name: change config
    tags: ['never', 'init']
    template:
      src: ./conf/{{ item }}
      dest: "{{ service_dir }}/conf/{{ item }}"
    with_items:
    - etcd.yaml

  - name: change compose
    tags: ['never', 'init']
    blockinfile:
      backup: no
      marker: '# {mark} SERVICE FOR ETCD'
      path: "{{ fs_compose_dir }}/docker-compose.yml"
      block: |
        # Do not modify manually
          etcd:
            restart: "${RESTART}"
            network_mode: host
            build:
              context: ./service/etcd
              args:
                - ETCD_VERSION=${ETCD_VERSION}
            environment:
              ETCD_ROOT_PASSWORD: ${ETCD_ROOT_PASSWORD}
            entrypoint: ["/usr/local/bin/etcd", "--config-file=/etc/etcd/etcd.yaml"]
            volumes:
              - ${DATA_DIR}/etcd:/var/etcd
              - ./service/etcd/conf/etcd.yaml:/etc/etcd/etcd.yaml
              - {{ fs_compose_dir }}/service/etcd/conf/ssl:/etc/etcd/ssl
